title: "Ali Eric Chinonso"
description: "Cybersecurity Researcher"
position: "Master Researcher\nHuazhong University of Science and Technology"
baseurl: ""
url: "https://empirenetwork123.github.io"
email: "Ericchinonso1@outlook.com"
linkedin_username: "ericchinonso"
github_username: "EmpireNetwork123"
scholar_link: "https://scholar.google.com/citations?user=88vHMEMAAAAJ"
about_me: "I a postgraduate researcher at Huazhong University of Science and Technology, working on wide range of cybersecurity research including Information Security, AI/ML applications, Deep Federated Learning, and Privacy and Security. Adept at communicating technical solutions to scientists, analysts, and business stakeholders. Committed to delivering innovative, efficient, and secure solutions that enhance system performance and regulation compliance."
markdown: kramdown
theme: null
