# ------------------------------------------
# PERSONAL INFO
# ------------------------------------------
title: "Ali Eric Chinonso"
description: "Cybersecurity Researcher"

# Two‑line subtitle for hero section
role: "Master Researcher"
affiliation: "Huazhong University of Science and Technology"

# ------------------------------------------
# SITE & REPO SETTINGS
# ------------------------------------------
baseurl: ""   # keep empty for https://empirenetwork123.github.io
url: "https://empirenetwork123.github.io"

# ------------------------------------------
# CONTACT / SOCIAL LINKS
# ------------------------------------------
email: "Ericchinonso1@outlook.com"
github_username: "EmpireNetwork123"
linkedin_username: "ericchinonso"
scholar_link: "https://scholar.google.com/citations?user=88vHMEMAAAAJ"

# ------------------------------------------
# ABOUT‑ME PARAGRAPH (Markdown accepted)
# ------------------------------------------
about_me: |
 My research mainly focus on information and digital forensics, am  experienced in adversarial modeling, privacy-preserving malware detection, and provenance analysis.
 My recent work applies artificial intelligence to detect and explain malicious behaviors especially those that apply polymophic attributes.
 I aim to extend these methods to AI-driven and IoT forensic investigations, building reliable tools for evidence attribution and secure networked systems.
# ------------------------------------------
markdown: kramdown
theme: null
